#spring:
#  application:
#    name: lms-auth-service
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/lms_db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
#  security:
#    jwt:
#      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # 24 hours in milliseconds
#
#server:
#  port: 8080
#
#logging:
#  level:
#    root: INFO
#    com.lms: DEBUG
#    org.springframework.security: DEBUG
#
## Swagger/OpenAPI Configuration
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
#    tryItOutEnabled: true
#
#
#rustici:
#  base-url: https://cloud.scorm.com/api/v2
#  app-id: LLNHO50Q7N
#  secret: 8iHpFotQEwZ73Qjn0MZIMpkCbjbAgdmztKaQqRlY
#
